# Generated by Django 5.0.1 on 2024-02-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_options_customuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.TextField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.TextField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.TextField(blank=True, max_length=15),
        ),
    ]
