# Generated by Django 5.0.1 on 2024-02-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=250)),
                ('cooking_time', models.CharField(max_length=50)),
                ('calorie', models.CharField(max_length=20)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
