# Generated by Django 5.0.1 on 2024-02-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_recipemodel_options_recipemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='image',
            field=models.ImageField(blank=True, default='recipe_image/default_image.jpg', upload_to='recipe_image/'),
        ),
    ]
