# Generated by Django 5.0.1 on 2024-02-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_recipemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
