# Generated by Django 5.0.1 on 2024-02-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_recipemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='create_at',
            field=models.DateTimeField(default='2023-04-17 16:58:31.317459-04:00'),
        ),
    ]
