# Generated by Django 5.0.1 on 2024-02-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_recipemodel_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
