# Generated by Django 5.0.1 on 2024-02-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_recipemodel_notes_alter_recipemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
