# Generated by Django 5.0.1 on 2024-02-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_recipemodel_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='about',
            field=models.TextField(),
        ),
    ]
