# Generated by Django 5.0.1 on 2024-02-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
